### ISSUE TITLE
plotting multiple contours?

### ISSUE THREAD

**Issue by jlchan** [j-fu/GridVisualize.jl#8]
Is there a way to overlay multiple contour surface plots? `scalarplot` and `scalarplot!` seem to only support a single `flevel` value per plot object.

**Comment by j-fu** [comment]
... this is in the plans, it's merely an API upgrade, possibly slightly breaking...

**Comment by jlchan** [comment]
Thanks for the heads up! I can also take a look and try working on it if it would be helpful.

**Comment by j-fu** [comment]
Hi thanks for the offer - I have already a  quite clear mind-map for this one and it is in fact already half done (because it's fun...)
I am quite sure there will be more issues to be fixed later on...

**Comment by j-fu** [comment]
Should work in 0.3.1 now. Instead of `flevel` you specify  a vector `levels`, and by default they are transparent, controlled by `levelalpha`. `outline=false` needs to be replaced by `outlinealpha=0`.

**Comment by jlchan** [comment]
Thank you! Looking forward to trying it out.
